version: v1

labels:
  - label: 'feat'
    matcher:
      title: '^feat:.*'
  - label: 'fix'
    matcher:
      title: '^fix:.*'
  - label: 'chore'
    matcher:
      title: '^chore:.*'
  - label: 'docs'
    matcher:
      title: '^docs:.*'
