// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ExampleSupplyChain$Type } from "./ExampleSupplyChain";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExampleSupplyChain"]: ExampleSupplyChain$Type;
    ["contracts/ExampleSupplyChain.sol:ExampleSupplyChain"]: ExampleSupplyChain$Type;
  }
}
